

services:
  db:
    image: postgres:16-alpine
    container_name: app-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:


    build:
      dockerfile: Dockerfile

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-appdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-appuser}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      # Optional JVM tuning; you can remove or tweak
      JAVA_OPTS: ${JAVA_OPTS:--XX:MaxRAMPercentage=75.0 -XX:+UseG1GC}

    ports:
      - "8080:8080"
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    depends_on:
      - app
    environment:
      # Point the UI (running in the browser) at your app’s OpenAPI endpoint
      URLS: '[{"url":"http://localhost:8080/v3/api-docs","name":"store"}]'
      URLS_PRIMARY_NAME: store
    ports:
      - "8081:8080"

volumes:
  pgdata:
